title: "Soheil Khatibi"
description: "MSc in CS at Lakehead University"
author: Soheil Khatibi
email: soheil.khatibi@example.com
baseurl: "" # Leave this blank for GitHub Pages
url: "https://SoheilKhatibi.github.io"
theme: jekyll-theme-minimal
custom_css:
  - css/styles.css
