title: "Soheil Khatibi"
description: "Machine Learning | Robotics | Data Science"
author: Soheil Khatibi
email: soheil.khatibi@example.com
baseurl: "" # Leave blank for GitHub Pages
url: "https://SoheilKhatibi.github.io"
theme: minimal
